### ISSUE TITLE
Segmentation fault when using cuda graph option

### ISSUE THREAD

**Issue by turnmanh** [Tractables/pyjuice#11]
Getting a segmentation fault when unsing cuda's graph option in the examples. To reproduce, run the `train_mnist_hclt.py` example as it. 

```
$ python examples/train_mnist_hclt.py
Compiling 51 TensorCircuit layers...
100%|...| 51/51 [00:03<00:00, 12.83it/s]
Segmentation fault (core dumped)
```

Note, the issue is mitigated using `train_mnist_hclt(enable_cudagrph=False)`.

**Comment by liuanji** [comment]
Thanks for reporting. I wasn't able to reproduce the bug locally. Could you share the version of the installed pytorch and triton? And maybe also for the cudatoolkit? Thanks.

**Comment by liuanji** [comment]
Closing this for now due to inactivity. Feel free to reopen if the problem persists.
