### ISSUE TITLE
Retrieving parameters from input node distribution

### ISSUE THREAD

**Issue by mjojic** [Tractables/pyjuice#18]
An algorithm I am implementing requires me, given an instance of an InputNode class to retrieve the probability of a variable associated with it taking on an assignment. I would want to just store that value from the em function for the input layer while training as it updates, but long story short, the fact that it is a static method is making this difficult.

The alternate options I have come up with seem more complicated then they need to be, so I am thinking there must be a simple way for me to get this parameter that I am missing. 
Maybe the thing making it complicated is that at the time I will only have the inputnode and need to get the param from there, since I am descending down the DAG from the pc's root_ns

If there is a better way for me to do this without extending the distribution class, and changing the EM function to a class method, I'd really appreciate to hear it

**Comment by liuanji** [comment]
Hi mjojic,

The following is a simple way to retrieve the parameters.

We start by defining a PC and compile it.
```py
>>> import torch
>>> import pyjuice as juice
>>> import pyjuice.nodes.distributions as dists
>>> ni = juice.inputs(0, num_node_blocks = 2, dist = dists.Categorical(num_cats = 2))
>>> ns = juice.summate(ni, num_nodes = 1)
>>> pc = juice.compile(ns)
>>> device = torch.device("cuda:0")
>>> pc.to(device)
```

We can then optimize the parameter of `pc` or do whatever we want on it.

Afterwards, when we need to get the parameters, we just need to do
```py
>>> pc.update_parameters()
```

which converts the packed parameters in `pc` back to the `CircuitNodes` (i.e., `ni` and `ns`). Then we can access the parameters of `ni` via `ni._params`.

For the case of categorical distributions with C categories and N input nodes, the returned tensor will have size N * C. We simply need to reshape it to `[N, C]` and then the ith row represents the parameters of the ith input node.

Best,
Anji

**Comment by mjojic** [comment]
Thank you!
