### ISSUE TITLE
Unsupported conversion from bf16 to f16 

### ISSUE THREAD

**Issue by isurulucky** [Tractables/pyjuice#20]
Hi, 

I get the following error from Triton when trying to run the train a pc example [1].

```
Unsupported conversion from bf16 to f16

UNREACHABLE executed at /project/lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp:816!
Aborted

```

I'm in the main branch; using version ```2.2.0``` for both ```torch``` and ```triton```, along with ```python``` version ```3.11.9```. Is there a known set of dependency versions which are working? Thanks in advance. 

BR, 
Isuru

[1]. https://tractables.github.io/pyjuice/getting-started/tutorials/01_train_pc.html#sphx-glr-getting-started-tutorials-01-train-pc-py

**Comment by liuanji** [comment]
Hi Isuru,

The problem may be caused by the GPU computing capability or the CUDA driver being too old. bf16 may not be supported in older GPUs. 

I would recommend passing `force_use_fp32=True` in the forward pass to see if the problem goes away:
```py
lls = pc(x, force_use_fp32=True)
```

Best,
Anji

**Comment by isurulucky** [comment]
Hi Anji, 

Thanks for the input. However, setting ```force_use_fp32=True``` gave rise to another error: 

```
LLVM ERROR: Cannot select: intrinsic %llvm.nvvm.shfl.sync.bfly.i32
Aborted
```

The node that I'm running computations on has a bunch of GeForce GTX 1080 GPUs (GP102 and GP104) and an ASPEED GPU. Could this be the issue? Is there by any chance a list of GPUs on which pyjuice works?

BR, 
Isuru

**Comment by liuanji** [comment]
I think so. GTX 1080 is probably not well supported by triton. Since pyjuice is heavily using triton it will also not work well. Below is an incomplete list of where pyjuice can work.

- RTX 4090
- A5000
- TITAN RTX
- A100/A800

Best,
Anji

**Comment by isurulucky** [comment]
Thanks Anji.

BR, 
Isuru.
